server:
  port: 8082
  servlet:
    context-path: /sensor-simulator
    
sensor:
  message:
    metrics:
      - temperature
      - oxygen
      - light 
    environmental-risk-amount: 20 
    
kafka:
  channel:
    configs:
      bootstrap-server: localhost:9092  
      topic-name: sensor-message-topic